framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # Dedicated Redis-backed cache pool for application data
        pools:
            products:
                adapter: cache.adapter.redis
                provider: 'redis://redis:6379'
